### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by diegoarioza** [ntop/ntopng-grafana-datasource#1]
Unknown error, when click in "save and test"

**Comment by simonemainardi** [comment]
please, post a screenshot of the configuration page

**Comment by tatianab85** [comment]
Hi, when i try to add the ntop data source in grafana I get an unknown error.. is there something i should configure in Ntop?

Thanks.

**Comment by simonemainardi** [comment]
- make sure you are using ntopng 3.1
- send a screen capture of the datasource configuration page

**Comment by tatianab85** [comment]
@simonemainardi , Hi
  Ntop version: v.3.0.170928  i get this error in ntopng
29/Sep/2017 11:22:30 [HTTPserver.cpp:820] ERROR: Unable to start HTTP server (IPv4) on ports 3000
![image](https://user-images.githubusercontent.com/28825221/31022478-8a6352d8-a4fe-11e7-8684-096fa425aa55.png)

**Comment by simonemainardi** [comment]
hi, please move to ntopng 3.1, version 3.0 does not have grafana support

**Comment by tatianab85** [comment]
@simonemainardi Hi, I don't seem to find the version 3.1 to upgrade from version 3.0.

**Comment by tatianab85** [comment]
@simonemainardi Hi, can you please let me know where i can find version 3.1, ntop website has it until version 3.0.. thanks..

**Comment by simonemainardi** [comment]
visit http://packages.ntop.org/ and follow the instructions to install the nightly build

**Comment by tatianab85** [comment]
Thanks @simonemainardi , all is working now ..
One last question, is it possible to have the application graph per remote host, right now I was able just to get the graph for the interfaz, as you can see in the graph..

Note: i'm using ntopng with nprobe. 

![image](https://user-images.githubusercontent.com/28825221/31085700-85bc10b0-a75d-11e7-925b-2f81b6d81025.png)

**Comment by simonemainardi** [comment]
timeseries are not stored nor provided for remote hosts. Make sure to define your local networks to contain all the hosts of interest.

So if you are interested to one particulare 'remote host', just use ntopng option -m to define it as local and you will get all the traffic timeseries
