### ISSUE TITLE
FR - add new useful metrics/timeseries

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng-grafana-datasource#10]
I released this simple patch to add some useful metrics/timeseries to the datasource:

[ntop_grafana_patch.txt](https://github.com/ntop/ntopng-grafana-datasource/files/1770766/ntop_grafana_patch.txt)

Could you add this new metrics/timeseries into your datasource?
I think that It could be useful also add other metrics/timeseries... ;-)

Thanks...

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
