### ISSUE TITLE
Scripts not working with grafana 5.2

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng-grafana-datasource#11]
Hello,

I migrate to grafana 5.2 and the NtopNG plugin does not work any more and returns an error on all panels.
<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script "/usr/share/ntopng/scripts/lua/modules/grafana/query.lua" returned an error: <p><H3>/usr/share/ntopng/scripts/lua/modules/grafana/query.lua:22: attempt to index field 'payload' (a nil value)</H3></body></html>". Parse error: "{}" http://errors.angularjs.org/1.6.6/$http/baddata?p0=HTTP/1.1 500 Internal server error
Content-Type: text/html
Connection: close

<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/usr/share/ntopng/scripts/lua/modules/grafana/query.lua&quot; returned an error:
<p><H3>/usr/share/ntopng/scripts/lua/modules/grafana/query.lua:22: attempt to index field 'payload' (a nil value)</H3></body></html>&p1={}

Regards

JP P

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
