### ISSUE TITLE
Datasourc fails in installation.

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng-grafana-datasource#2]
1. The official ntopng Grafana datasource plugin lets you quickly navigate ntopng data from inside the beautiful Grafana dashboards. Cannot find on the grafana web site.

2. Installing the version in github in the directory /usr/share/grafana/public/app/plugins/datasource/ntopng

Allows the datasource to been visible, but when you enter the type, all the settings
fields disappear (HTTP settings, HTTP auth), and that remains are the name and type fields.

It is then impossible to proceed further.

**Comment by portalthiago** [comment]
Hello guys, i am havim troubles to make the api found a match and im not have even a message to help me in to a troubleshooting.

**Comment by ghost** [comment]
Hi
As I never got a response, I developed my own network monitoring system, utilising Grafana, Influxdb, postgresql, rabbitmq, Telegraph and pmacctd. This allows flow monitoring, with snmp to monitor the router traffic. This approach removes the dependancy on ntopng.

**Comment by ghost** [comment]
Closed due to no response from ntopng
