### ISSUE TITLE
Error with connecting to datasource

### ISSUE THREAD

**Issue by animosity022** [ntop/ntopng-grafana-datasource#5]
I have a new install on Fedora 27 with Grafana already working without issue.

I compiled ntopng this morning and it seems to be working fine:

ntopng --version
v.3.3.180129	[Community build]

I'm using a connection like this and I hit save and test and it gives me a red error box without any text.

![image](https://user-images.githubusercontent.com/5088712/35533552-e6257e12-050b-11e8-9e76-1250f7756268.png)

If I drop an extra / on the end, I can see the pages seems to be there without an issue:

![image](https://user-images.githubusercontent.com/5088712/35533584-00726b7c-050c-11e8-9c37-b40809d406ab.png)

I'm also running with logins disabled so I have no auth checked for that reason.

**Comment by animosity022** [comment]
Retried on a clean install of Ubuntu 16.04 and that produced the same error.

**Comment by davnustratbac** [comment]
Getting the same thing here on CentOS 7 clean install, same red box with no text. Seems to fail with Basic Auth using default login / passwd combo . Ntop web interface working fine connecting directly

**Comment by davnustratbac** [comment]
OK so.. running this command:
curl -H 'Accept: application/json' http://localhost:3001/lua/modules/grafana
Returns:
`<html><head><title>ntop</title></head><body><center><img src=/img/warning.png> Page &quot;/lua/modules/grafana&quot; was not found</body></html>`

Looking at this this [post](https://community.grafana.com/t/cannot-connect-test-to-local-ntopng-datasource/3645/2) shows support only for builds 3.1 
my version is 3.2
So checking the ntopng install tree shows:
/usr/share/ntopng/scripts/lua/modules/grafana/query.lua
/usr/share/ntopng/scripts/lua/modules/grafana/search.lua

so checking permissions reveals:
ls -al /usr/share/ntopng/scripts/lua/modules/grafana/index.lua
-rw-r--r--. 1 root root 611 Jan 29 15:08 /usr/share/ntopng/scripts/lua/modules/grafana/index.lua
from there if we check the user who ntopng is running as:
nobody   16177     1  0 21:34 ?        00:00:30 /usr/local/bin/ntopng /run/ntopng.conf

Ive not got any further with it but I thought id share what I have found

**Comment by animosity022** [comment]
I can do a bunch of wgets on the items in the grafana folder.Anyone have this working that can share some more details?

**Comment by animosity022** [comment]
I played around a bit more and turned up the logging and I can see it finds the grafana link but still seems to bomb out:

```
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [Lua.cpp:6536] [ntop_lua_require] Searching /usr/share/ntopng/scripts/lua/modules/i18n/grafana_utils.lua
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [Lua.cpp:6536] [ntop_lua_require] Searching /usr/share/ntopng/scripts/lua/modules/grafana_utils.lua
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [Lua.cpp:6540] [ntop_lua_require] Found /usr/share/ntopng/scripts/lua/modules/grafana_utils.lua
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [Lua.cpp:4777] ntop_get_dirs() called
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [Lua.cpp:4832] ntop_get_info() called
Feb 15 08:57:29 plex ntopng[16659]: 15/Feb/2018 08:57:29 [HTTPserver.cpp:157] [HTTP] Set session
```

**Comment by animosity022** [comment]
anyone?

**Comment by davnustratbac** [comment]
Ive got to be honest I havnt had any time to look at this any further, i was using ntopng to diagnose a performance issue with a server, only to find the cpu overhead running it caused more problems than it solved. During the process I gave up on this plugin and just used the standard ntopng interface.
In debugging this further it might be useful to see if something like a netcat variant or socat can act as a proxy through and see if you can tee the output. Im seeing this is built in angular, Im wondering if the 'fetch' library is being employed in the angular code ? Might be worth pulling the code and seeing if theres any further debugging that can be enabled there.

**Comment by animosity022** [comment]
That's beyond my skill set. I'm just hoping someone that supports it can help out to say why it doesn't work.

**Comment by animosity022** [comment]
Any help?

**Comment by ajcollett** [comment]
I have this issue too. I don't know how to draw more attention to it. I have ntopng 3.2 on FreeBSD, ntopng working fine, I can see the Json returned from `/lua/modules/grafana/` (specifically with the last `/`) but still, an errorless red bar and no metrics when I try setup a graph. My dockerised grafana is also showing influxdb entries happily. 

Edit: @daniellee Do you have any ideas?

Edit 2: I even downgraded to the latest 4.X docker image, still the same error.

**Comment by ajcollett** [comment]
OKAY! I found my issue. I had my grafana on HTTPS and the ntopng instance on HTTP and found an error in the console about cross site referencing. So I secured the ntopng instance and boom! It works. The error output is not very nice, because if it does not resolve the host it also fails in the same way.

**Comment by animosity022** [comment]
Hmm. I'll see as I reverse proxy my grafana and my ntopng through apache.

**Comment by daniellee** [comment]
This is due to the ntopng plugin for Grafana using Direct mode (direct means direct from your browser to ntopng and does not go through the Grafana backend) - most plugins use proxy mode to avoid this type of issue (cross-origin errors being another example).

**Comment by animosity022** [comment]
I'm aware it's direct.

I am trying to set it while connected locally on my network via a VPN. I have Grafana setup via a reverse proxy and my connection works using http: locally as I posted above. I can connect properly from my browser.

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
