### ISSUE TITLE
Hide Interface name

### ISSUE THREAD

**Issue by chuyendang** [ntop/ntopng-grafana-datasource#7]
Can I hide ntopng interface name on Grafana  ([tcp://127.0.0.1:5556] ) ?

![image](https://user-images.githubusercontent.com/8739593/36653328-01e194ec-1ae7-11e8-8403-826286dd6a5a.png)

Thanks,

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
