### ISSUE TITLE
FR - Legend entries

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng-grafana-datasource#8]
Could you add the possibility to change the strings of the legend entries?
As you can see here

![legend_entries](https://user-images.githubusercontent.com/14093378/36837774-92a20eaa-1d3d-11e8-9f74-7c81b7b93c9b.png)

is not important to know the name of the zc interface (zc:2@0) but could be useful change it with the string "IT Office".
I saw some examples on the web where it was possible to use the command "ALIAS BY" into the datasource.
Could you add this feature into the ntopng datasource?
Thanks...

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
