### ISSUE TITLE
FR - "other protocols" into the allprotocols_bps timeserie

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng-grafana-datasource#9]
As you can see into this image:

![grafana](https://user-images.githubusercontent.com/14093378/36839295-03884946-1d42-11e8-9f81-f702ebc84ac2.png)

with the timeserie "interface_zc:2@0_allprotocols_bps" we can see only the first 10 protocols discovered by ntopng.
I have just 2 feature request:
1) Could you add the possibility to change the number of protocols shown into the graph? (In instance from 10 to 15 or from 10 to 5)
2) Into the graph now we see only the first 10 protocols but we haven't any information about to the other protocols detected by ntopng. It could be useful to add a new graph into this timeserie called "Other protocols" useful to understand what happen into the monitored network.

Could you add these features?

Thanks...

**Comment by simonemainardi** [comment]
Closing as plugin support has been discontinued in favour of https://grafana.com/docs/features/datasources/influxdb/. See the README  https://github.com/ntop/ntopng-grafana-datasource.
